services:
  traefik:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tismoj-gamedev@trackmyownfiles.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # Add new entrypoints for Minio ports if you want Traefik to handle TLS on them
      - "--entrypoints.minio-server.address=:9000"
      - "--entrypoints.minio-console.address=:9001"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
      # Publish the new entrypoint ports on the host if needed for external access
      - mode: host
        protocol: tcp
        published: 9000
        target: 9000
      - mode: host
        protocol: tcp
        published: 9001
        target: 9001
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-data:/data
      - /DockerContainers/traefik_logs:/var/log/traefik

  web:
    image: ghcr.io/tismoj/zenstats:${GIT_COMMIT_HASH:-latest}
#    image: ghcr.io/dreamsofcode-io/zenstats:broken-quote
#    image: ghcr.io/dreamsofcode-io/zenstats:baaf221054f44ec2b6d85f60e94b70a0619665be
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.web.loadbalancer.server.port=8080"
      - "traefik.http.routers.web.rule=Host(`contabo-cvps-n1.trackmyownfiles.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
    secrets:
      - db-password
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
      - POSTGRES_SSLMODE=disable
    deploy:
      update_config:
        parallelism: 1
        max_failure_ratio: 0.80
        failure_action: rollback
        order: start-first
    depends_on:
      - db

  db:
    image: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    image: docker.n8n.io/n8nio/n8n
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.n8n.loadbalancer.server.port=443"
      - "traefik.http.routers.n8n.rule=Host(`n8n.contabo-cvps-n1.trackmyownfiles.com`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"
    volumes:
      - n8n-data:/home/node/.n8n
    environment:
      - N8N_HOST=n8n.contabo-cvps-n1.trackmyownfiles.com
      - N8N_PORT=443
      - N8N_PROTOCOL=https

  minio:
    image: quay.io/minio/minio
    labels:
      - "traefik.enable=true"
      # Minio Server (Port 9000)
      - "traefik.http.services.minio-server.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-server.rule=Host(`minio.contabo-cvps-n1.trackmyownfiles.com`)"
      - "traefik.http.routers.minio-server.entrypoints=minio-server" # Use the new entrypoint
      - "traefik.http.routers.minio-server.service=minio-server@docker" # Explicitly link to the 'minio-server' service
      # If you want TLS on this port, uncomment the following
      - "traefik.http.routers.minio-server.tls=true"
      - "traefik.http.routers.minio-server.tls.certresolver=myresolver"
      # Minio Console (Port 9001)
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio-console.rule=Host(`minio.contabo-cvps-n1.trackmyownfiles.com`)"
      - "traefik.http.routers.minio-console.entrypoints=minio-console" # Use the new entrypoint
      - "traefik.http.routers.minio-console.service=minio-console@docker" # Explicitly link to the 'minio-console' service
      # TLS is generally not needed for the console on a separate port, but you can add it if desired
      - "traefik.http.routers.minio-console.tls=true"
      - "traefik.http.routers.minio-console.tls.certresolver=myresolver"
    volumes:
      - minio-data:/data
    secrets:
      - minio-root-password
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD_FILE=/run/secrets/minio-root-password
    command: ["server", "/data", "--console-address", ":9001"]

volumes:
  db-data:
  letsencrypt:
  n8n-data:
  minio-data:
    external: true
  traefik-data:

secrets:
  db-password:
    external: true
  minio-root-password:
    external: true
